AWSTemplateFormatVersion: "2010-09-09"
Description: "Inventory Management System â€“ ECS Fargate with ALB, DynamoDB access, Default VPC"

Parameters:
  InventoryApiEcrImage:
    Type: String
    Description: "ECR image URI for Inventory FastAPI service"

  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Default VPC public subnets"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "Default VPC ID"

  AcmCertificateArn:
    Type: String
    Description: "ACM certificate ARN for HTTPS listener"

Resources:

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP/HTTPS from internet"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow traffic from ALB to ECS"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          SourceSecurityGroupId: !Ref AlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0


  InventoryAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: inventory-alb
      Scheme: internet-facing
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Subnets: !Ref PublicSubnets

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref InventoryAlb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref InventoryAlb
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AcmCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref InventoryTargetGroup

  InventoryTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: inventory-tg
      Port: 8000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: "/health"
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3


  InventoryCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: inventory-cluster


  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: inventory-task-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: inventory-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonCognitoDeveloperAuthenticatedIdentities
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess


  InventoryLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/inventory-fastapi
      RetentionInDays: 14


  InventoryTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: inventory-fastapi-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: inventory-api
          Image: !Ref InventoryApiEcrImage
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp

          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref InventoryLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: inventory

          HealthCheck:
            Command:
              ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
            StartPeriod: 60

          Environment:
            - Name: table_name
              Value: Inventory_Management
            - Name: topic_arn
              Value: arn:aws:sns:ap-south-1:915908749134:simpleEmailSNS
            - Name: COGNITO_ISSUER
              Value: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_VEJtqqSuE
            - Name: JWKS_URL
              Value: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_VEJtqqSuE/.well-known/jwks.json
            - Name: USER_POOL_ID
              Value: ap-south-1_VEJtqqSuE
            - Name: COGNITO_REGION
              Value: ap-south-1
            - Name: COGNITO_CLIENT_ID
              Value: 42p8mhr9lgrj8na2itajc1rr05


  InventoryService:
    Type: AWS::ECS::Service
    DependsOn:
      - HttpListener
    Properties:
      ServiceName: inventory-fastapi-service
      Cluster: !Ref InventoryCluster
      TaskDefinition: !Ref InventoryTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref EcsSecurityGroup
          Subnets: !Ref PublicSubnets
      LoadBalancers:
        - TargetGroupArn: !Ref InventoryTargetGroup
          ContainerName: inventory-api
          ContainerPort: 8000


Outputs:
  InventoryApiURL:
    Description: "Inventory Management API endpoint"
    Value: !GetAtt InventoryAlb.DNSName
